export type IslandQuarterMap = Record<string, string>;

export const STT_ESTATE_QUARTERS: IslandQuarterMap = {
  bethesda: "Westend Quarter",
  "bonne esperance": "Westend Quarter",
  bordeaux: "Westend Quarter",
  botanybay: "Westend Quarter",
  "catherines hope": "Westend Quarter",
  contant: "Westend Quarter",
  fortuna: "Westend Quarter",
  hope: "Westend Quarter",
  perseverance: "Westend Quarter",

  caretbay: "Little Northside Quarter",
  "caret bay": "Little Northside Quarter",
  dorothea: "Little Northside Quarter",
  neltjeberg: "Little Northside Quarter",

  adelphi: "Southside Quarter",
  altona: "Southside Quarter",
  cabrite: "Southside Quarter",
  "mosquito bay": "Southside Quarter",

  canaan: "Great Northside Quarter",
  lerkenlund: "Great Northside Quarter",
  lovenlund: "Great Northside Quarter",
  mandal: "Great Northside Quarter",
  solberg: "Great Northside Quarter",

  "charlotte amalia": "New (Prince George) Quarter",
  donoe: "New (Prince George) Quarter",
  tutu: "New (Prince George) Quarter",
  "annas retreat": "New (Prince George) Quarter",
  "anna s retreat": "New (Prince George) Quarter",
  wintberg: "New (Prince George) Quarter",

  bolongo: "French Bay Quarter",
  bovoni: "French Bay Quarter",
  stalley: "French Bay Quarter",

  frydendal: "Eastend Quarter",
  smithbay: "Eastend Quarter",
  "smith bay": "Eastend Quarter",

  benner: "Redhook Quarter",
  mariendal: "Redhook Quarter",
  nadir: "Redhook Quarter",
  nazareth: "Redhook Quarter",

  "water island": "Water Island Quarter",
  waterisland: "Water Island Quarter",
};

export const STJ_ESTATE_QUARTERS: IslandQuarterMap = {
  adrian: "Cruz Bay Quarter",
  bethany: "Cruz Bay Quarter",
  beverhoutberg: "Cruz Bay Quarter",
  contant: "Cruz Bay Quarter",
  durloe: "Cruz Bay Quarter",
  "klein caneel": "Cruz Bay Quarter",
  "klein caneel estate": "Cruz Bay Quarter",
  "hammer farm": "Cruz Bay Quarter",
  susannaberg: "Cruz Bay Quarter",
  enighed: "Cruz Bay Quarter",
  catherineberg: "Cruz Bay Quarter",

  "america hill": "Maho Quarter",
  annaberg: "Maho Quarter",
  "cinnamon bay": "Maho Quarter",
  mahobay: "Maho Quarter",
  "maho bay": "Maho Quarter",
  rustenberg: "Maho Quarter",
  windberg: "Maho Quarter",

  hope: "Reef Bay Quarter",
  lameshur: "Reef Bay Quarter",
  molendal: "Reef Bay Quarter",
  parforce: "Reef Bay Quarter",
  reefbay: "Reef Bay Quarter",
  "reef bay": "Reef Bay Quarter",
  seeven: "Reef Bay Quarter",
  sieben: "Reef Bay Quarter",

  carolina: "Coral Bay Quarter",
  emmaus: "Coral Bay Quarter",
  emaus: "Coral Bay Quarter",
  bordeaux: "Coral Bay Quarter",
  "johns folly": "Coral Bay Quarter",
  "john's folly": "Coral Bay Quarter",
  mandal: "Coral Bay Quarter",

  oostende: "Eastend Quarter",
  eastend: "Eastend Quarter",
  "east end": "Eastend Quarter",
  bethania: "Cruz Bay Quarter",
};

export const STX_ESTATE_QUARTERS: IslandQuarterMap = {
  annaly: "Northside A Quarter",
  bodkin: "Northside A Quarter",
  "butler bay": "Northside A Quarter",
  caledonia: "Northside A Quarter",
  crequis: "Northside A Quarter",
  "mount stewart": "Northside A Quarter",
  "mount victory": "Northside A Quarter",
  "mount washington": "Northside A Quarter",
  northside: "Northside A Quarter",
  oxford: "Northside A Quarter",
  prosperity: "Northside A Quarter",
  punch: "Northside A Quarter",
  william: "Northside A Quarter",

  belvedere: "Northside B Quarter",
  canaan: "Northside B Quarter",
  canebay: "Northside B Quarter",
  "cane bay": "Northside B Quarter",
  clairmont: "Northside B Quarter",
  lavallee: "Northside B Quarter",
  "la vallee": "Northside B Quarter",
  "little fountain": "Northside B Quarter",
  northstar: "Northside B Quarter",
  parasol: "Northside B Quarter",
  rustoptwist: "Northside B Quarter",
  solitude: "Northside B Quarter",

  "beck grove": "Westend Quarter",
  "becks grove": "Westend Quarter",
  "bonne esperance": "Westend Quarter",
  brook: "Westend Quarter",
  camporico: "Westend Quarter",
  cane: "Westend Quarter",
  canevalley: "Westend Quarter",
  "cane valley": "Westend Quarter",
  carlton: "Westend Quarter",
  "lower concordia": "Westend Quarter",
  goodhope: "Westend Quarter",
  "good hope": "Westend Quarter",
  "hannahs rest": "Westend Quarter",
  "hannah's rest": "Westend Quarter",
  hesselberg: "Westend Quarter",
  hogensborg: "Westend Quarter",
  hope: "Westend Quarter",
  "jolly hill": "Westend Quarter",
  lagrange: "Westend Quarter",
  "little grange": "Westend Quarter",
  "mars hill": "Westend Quarter",
  "ruan bay": "Westend Quarter",
  rowans: "Westend Quarter",
  smithfield: "Westend Quarter",
  stonyground: "Westend Quarter",
  "stony ground": "Westend Quarter",
  "two brothers": "Westend Quarter",
  "two williams": "Westend Quarter",
  wade: "Westend Quarter",
  waldberggaard: "Westend Quarter",
  whim: "Westend Quarter",
  white: "Westend Quarter",
  "wheel of fortune": "Westend Quarter",
  "wheel-of-fortune": "Westend Quarter",
  "williams delight": "Westend Quarter",
  "william's delight": "Westend Quarter",

  adventure: "Prince Quarter",
  allandale: "Prince Quarter",
  "bettys hope": "Prince Quarter",
  "betty's hope": "Prince Quarter",
  "castle burke": "Prince Quarter",
  clermont: "Prince Quarter",
  concordia: "Prince Quarter",
  cooper: "Prince Quarter",
  montpellier: "Prince Quarter",
  diamond: "Prince Quarter",
  "enfield green": "Prince Quarter",
  envy: "Prince Quarter",
  fox: "Prince Quarter",
  "golden grove": "Prince Quarter",
  groveplace: "Prince Quarter",
  "grove place": "Prince Quarter",
  hardlabor: "Prince Quarter",
  "hard labor": "Prince Quarter",
  hermitage: "Prince Quarter",
  "lower love": "Prince Quarter",
  "manning bay": "Prince Quarter",
  "mannings bay": "Prince Quarter",
  mint: "Prince Quarter",
  "mount pleasant": "Prince Quarter",
  negrobay: "Prince Quarter",
  "negro bay": "Prince Quarter",
  "old pye": "Prince Quarter",
  paradise: "Prince Quarter",
  plessen: "Prince Quarter",
  "st george": "Prince Quarter",
  "st. george": "Prince Quarter",
  "upper love": "Prince Quarter",
  waterground: "Prince Quarter",
  "water ground": "Prince Quarter",

  atkins: "Queen (Dronning) Quarter",
  barrenspot: "Queen (Dronning) Quarter",
  "barren spot": "Queen (Dronning) Quarter",
  "barren spot west": "Queen (Dronning) Quarter",
  "barren spot east": "Queen (Dronning) Quarter",
  "cassava garden": "Queen (Dronning) Quarter",
  "castle coakley": "Queen (Dronning) Quarter",
  "constitution hill": "Queen (Dronning) Quarter",
  glynn: "Queen (Dronning) Quarter",
  humbug: "Queen (Dronning) Quarter",
  jerusalem: "Queen (Dronning) Quarter",
  lareine: "Queen (Dronning) Quarter",
  "la reine": "Queen (Dronning) Quarter",
  limetree: "Queen (Dronning) Quarter",
  "lime tree": "Queen (Dronning) Quarter",
  morningstar: "Queen (Dronning) Quarter",
  "morning star": "Queen (Dronning) Quarter",
  morning_star: "Queen (Dronning) Quarter",
  pearl: "Queen (Dronning) Quarter",
  "peters rest": "Queen (Dronning) Quarter",
  "peter's rest": "Queen (Dronning) Quarter",
  princess: "Queen (Dronning) Quarter",
  "grand princess": "Queen (Dronning) Quarter",
  "st john": "Queen (Dronning) Quarter",
  "st. john": "Queen (Dronning) Quarter",
  "sion farm": "Queen (Dronning) Quarter",
  "sion hill": "Queen (Dronning) Quarter",
  strawberry: "Queen (Dronning) Quarter",
  windsor: "Queen (Dronning) Quarter",

  annaberg: "King Quarter",
  barnspool: "King Quarter",
  "barn spool": "King Quarter",
  bethlehem: "King Quarter",
  blessing: "King Quarter",
  "caramaw hall": "King Quarter",
  "clifton hill": "King Quarter",
  "colquohoun mt pleasant": "King Quarter",
  lebanon: "King Quarter",
  midland: "King Quarter",
  "mon bijou": "King Quarter",
  profit: "King Quarter",
  slob: "King Quarter",
  spanishtown: "King Quarter",
  "spanish town": "King Quarter",

  "annas hope": "Company Quarter",
  "anna s hope": "Company Quarter",
  "anna's hope": "Company Quarter",
  "beeston hill": "Company Quarter",
  bellevue: "Company Quarter",
  contentment: "Company Quarter",
  cornhill: "Company Quarter",
  "diamond keturah": "Company Quarter",
  "golden rock": "Company Quarter",
  granard: "Company Quarter",
  grange: "Company Quarter",
  "hermon hill": "Company Quarter",
  "little princess": "Company Quarter",
  "mount welcome": "Company Quarter",
  "peters farm": "Company Quarter",
  "peter's farm": "Company Quarter",
  recovery: "Company Quarter",
  richmond: "Company Quarter",
  "work and rest": "Company Quarter",
  "work-and-rest": "Company Quarter",

  "all for the better": "Eastend A Quarter",
  "all-for-the-better": "Eastend A Quarter",
  beckmans: "Eastend A Quarter",
  "beckman's": "Eastend A Quarter",
  butzberg: "Eastend A Quarter",
  carina: "Eastend A Quarter",
  "salmon hill": "Eastend A Quarter",
  "castle nugent": "Eastend A Quarter",
  nugent: "Eastend A Quarter",
  "coakley bay": "Eastend A Quarter",
  cottongrove: "Eastend A Quarter",
  "cotton grove": "Eastend A Quarter",
  endracht: "Eastend A Quarter",
  fareham: "Eastend A Quarter",
  farrington: "Eastend A Quarter",
  greatpond: "Eastend A Quarter",
  "great pond": "Eastend A Quarter",
  greencay: "Eastend A Quarter",
  "green cay": "Eastend A Quarter",
  hartman: "Eastend A Quarter",
  petronella: "Eastend A Quarter",
  "prospect hill": "Eastend A Quarter",
  punnett: "Eastend A Quarter",
  "sallys fancy": "Eastend A Quarter",
  "sally's fancy": "Eastend A Quarter",
  sevenhills: "Eastend A Quarter",
  "seven hills": "Eastend A Quarter",
  shoys: "Eastend A Quarter",
  "shoy's": "Eastend A Quarter",
  southgate: "Eastend A Quarter",
  springs: "Eastend A Quarter",
  testman: "Eastend A Quarter",
  tipperary: "Eastend A Quarter",

  adjett: "Eastend B Quarter",
  carden: "Eastend B Quarter",
  carty: "Eastend B Quarter",
  "old coakley bay": "Eastend B Quarter",
  cottongarden: "Eastend B Quarter",
  "cotton garden": "Eastend B Quarter",
  hodge: "Eastend B Quarter",
  "marys fancy": "Eastend B Quarter",
  "mary's fancy": "Eastend B Quarter",
  "tague bay": "Eastend B Quarter",
  valley: "Eastend B Quarter",
};
