import type { CommunityContext, CommunityPost } from "@/types/community";

export const STT_COMMUNITY_CONTEXT: CommunityContext = {
  cruisePulse: "Havensight active today",
  ferryWatch: "Red Hook ferry moving smoothly",
  marineNote: "Northside moderate chop",
  seasonalNote: "Carnival energy building",
};

export const STT_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "pulse-town-1",
    district: "stt_stj",
    island: "stt",
    quarter: "new_prince_george",
    type: "pulse",
    title: "Town getting busier after 10",
    body:
      "Cruise foot traffic is building through Charlotte Amalie. Good time for a quick stop now, heavier movement later.",
    authorName: "Town Watch",
    authorHandle: "@townwatch",
    createdAt: Date.now() - 1000 * 60 * 22,
    estateGeoid: "7803017300",
    estateName: "Estate Charlotte Amalie",
    placeName: "Charlotte Amalie",
    likes: 121,
    replies: 21,
    verified: true,
    tags: ["town", "cruise", "daytime"],
  },
  {
    id: "ferry-east-end-1",
    district: "stt_stj",
    island: "stt",
    quarter: "redhook",
    type: "ferry",
    title: "Red Hook moving smooth right now",
    body:
      "Ferry side is active but not backed up. Good window if you are trying to cross before the afternoon push.",
    authorName: "Island Pulse",
    authorHandle: "@islandpulse",
    createdAt: Date.now() - 1000 * 60 * 16,
    estateGeoid: "7803058400",
    estateName: "Estate Nazareth",
    placeName: "Red Hook",
    likes: 84,
    replies: 12,
    verified: true,
    tags: ["ferry", "red hook", "st. john"],
  },
  {
    id: "northside-beach-1",
    district: "stt_stj",
    island: "stt",
    quarter: "great_northside",
    type: "beach",
    title: "Northside looks choppy today",
    body:
      "Beautiful light, but rougher water than usual. Better beach energy on the calmer side if you want an easy swim.",
    authorName: "Beach Scout",
    authorHandle: "@beachscoutvi",
    createdAt: Date.now() - 1000 * 60 * 64,
    estateGeoid: "7801060850",
    estateName: "Estate Northside",
    placeName: "Northside",
    likes: 93,
    replies: 15,
    tags: ["beach", "northside", "water"],
  },
  {
    id: "havensight-night-1",
    district: "stt_stj",
    island: "stt",
    quarter: "southside",
    type: "nightlife",
    title: "Good energy building around Havensight tonight",
    body:
      "Looks like a strong after-dark crowd later. Good zone if you want people, music, and movement without overplanning.",
    authorName: "VI Moves",
    authorHandle: "@vimoves",
    createdAt: Date.now() - 1000 * 60 * 90,
    estateGeoid: "7803047235",
    estateName: "Estate Havensight",
    placeName: "Havensight",
    likes: 74,
    replies: 9,
    tags: ["nightlife", "havensight", "tonight"],
  },
  {
    id: "crown-bay-food-1",
    district: "stt_stj",
    island: "stt",
    quarter: "westend",
    type: "food",
    title: "Good lunch window near Crown Bay",
    body:
      "Cruise-side traffic is lighter than Havensight right now. Good area if you want to grab food without Town-level movement.",
    authorName: "Taste VI",
    authorHandle: "@tastevi",
    createdAt: Date.now() - 1000 * 60 * 41,
    estateGeoid: "7803077150",
    estateName: "Estate Subbase and Crown Bay",
    placeName: "Crown Bay",
    likes: 67,
    replies: 8,
    tags: ["food", "crown bay", "lunch"],
  },
  {
    id: "mid-island-tip-1",
    district: "stt_stj",
    island: "stt",
    quarter: "eastend",
    type: "tip",
    title: "Tutu corridor is your reset zone today",
    body:
      "If Town and the dock side feel too active, mid-island is the easiest way to reset before heading back out.",
    authorName: "Local Lens",
    authorHandle: "@locallens",
    createdAt: Date.now() - 1000 * 60 * 120,
    estateGeoid: "7803005520",
    estateName: "Estate Annas Retreat",
    placeName: "Tutu",
    likes: 52,
    replies: 6,
    tags: ["tip", "mid-island", "local"],
  },
  {
    id: "event-town-1",
    district: "stt_stj",
    island: "stt",
    quarter: "new_prince_george",
    type: "event",
    title: "Carnival season is taking over Town",
    body:
      "Expect stronger social energy, more movement, and more reason to plan around events instead of only places.",
    authorName: "USVI Events",
    authorHandle: "@usvievents",
    createdAt: Date.now() - 1000 * 60 * 145,
    estateGeoid: "7803017300",
    estateName: "Estate Charlotte Amalie",
    placeName: "Charlotte Amalie",
    likes: 211,
    replies: 41,
    verified: true,
    tags: ["carnival", "event", "town"],
  },
];
